version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: warehouse
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    restart: on-failure
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db/warehouse
    ports:
      - "8000:8000"
    volumes:
      - .:/app /app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]  # Устанавливаем автоперезагрузку

volumes:
  pgdata: